remove non-working example
The example I propose removing uses the df[ ] operator.  Based on the code introduced by lesson 08, I don't think it works.  Specifically, after running: 
import pandas
path="python-novice-gapminder-data/data/gapminder_all.csv"
first = pandas.read_csv(path, index_col='country')
first.head()
# then the following fails, 
second = df[df['continent'] == 'Americas']
# with the error:
NameError                                 Traceback (most recent call last)
<ipython-input-68-460e46bc0b3f> in <module>()
----> 1 second = df[df['continent'] == 'Americas']
      2 second.head()

NameError: name 'df' is not defined

Is there an additional import statement that's missing?